In [ ]:
import re    # for regular expressions 
import nltk  # for text manipulation 
import string 
import warnings 
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt  


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
train = pd.read_csv("train.csv")


In [ ]:
train.head()

employee_id         department  ... avg_training_score is_promoted
0        65438  Sales & Marketing  ...                 49           0
1        65141         Operations  ...                 60           0
2         7513  Sales & Marketing  ...                 50           0
3         2542  Sales & Marketing  ...                 50           0
4        48945         Technology  ...                 73           0

[5 rows x 14 columns]

In [ ]:
train.dtypes

employee_id               int64
department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [ ]:
train.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [ ]:
train.shape

(54808, 14)

In [ ]:
test = pd.read_csv("test.csv")

In [ ]:
test.head()

employee_id         department  ... awards_won? avg_training_score
0         8724         Technology  ...           0                 77
1        74430                 HR  ...           0                 51
2        72255  Sales & Marketing  ...           0                 47
3        38562        Procurement  ...           0                 65
4        64486            Finance  ...           0                 61

[5 rows x 13 columns]

In [ ]:
test.isnull().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [ ]:
test.shape

(23490, 13)

In [ ]:

# filling missing values

train['education'].fillna(train['education'].mode()[0], inplace = True)
train['previous_year_rating'].fillna(1, inplace = True)

# again checking if there is any Null value left in the data
train.isnull().sum().sum()

0

In [ ]:

# filling missing values

test['education'].fillna(test['education'].mode()[0], inplace = True)
test['previous_year_rating'].fillna(1, inplace = True)

# again checking if there is any Null value left in the data
test.isnull().sum().sum()

0

In [ ]:
# removing the employee_id column

train = train.drop(['employee_id'], axis = 1)

train.columns

Index(['department', 'region', 'education', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score', 'is_promoted'],
      dtype='object')

In [ ]:

# saving the employee_id

emp_id = test['employee_id']

# removing the employee_id column

test = test.drop(['employee_id'], axis = 1)

test.columns

Index(['department', 'region', 'education', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score'],
      dtype='object')

In [ ]:
# defining the test set

x_test = test

x_test.columns

Index(['department', 'region', 'education', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score'],
      dtype='object')

In [ ]:
# one hot encoding for the test set

x_test = pd.get_dummies(x_test)

x_test.columns

Index(['no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score',
       'department_Analytics', 'department_Finance', 'department_HR',
       'department_Legal', 'department_Operations', 'department_Procurement',
       'department_R&D', 'department_Sales & Marketing',
       'department_Technology', 'region_region_1', 'region_region_10',
       'region_region_11', 'region_region_12', 'region_region_13',
       'region_region_14', 'region_region_15', 'region_region_16',
       'region_region_17', 'region_region_18', 'region_region_19',
       'region_region_2', 'region_region_20', 'region_region_21',
       'region_region_22', 'region_region_23', 'region_region_24',
       'region_region_25', 'region_region_26', 'region_region_27',
       'region_region_28', 'region_region_29', 'region_region_3',
       'region_region_30', 'region_region_31', 'region_region_32',
       'region_region_33', 'region_region_34', 'reg

In [ ]:

# splitting the train set into dependent and independent sets

x = train.iloc[:, :-1]
y = train.iloc[:, -1]

print("Shape of x:", x.shape)
print("Shape of y:", y.shape)

Shape of x: (54808, 12)
Shape of y: (54808,)


In [ ]:

# one hot encoding for the train set

x = pd.get_dummies(x)

x.columns

Index(['no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score',
       'department_Analytics', 'department_Finance', 'department_HR',
       'department_Legal', 'department_Operations', 'department_Procurement',
       'department_R&D', 'department_Sales & Marketing',
       'department_Technology', 'region_region_1', 'region_region_10',
       'region_region_11', 'region_region_12', 'region_region_13',
       'region_region_14', 'region_region_15', 'region_region_16',
       'region_region_17', 'region_region_18', 'region_region_19',
       'region_region_2', 'region_region_20', 'region_region_21',
       'region_region_22', 'region_region_23', 'region_region_24',
       'region_region_25', 'region_region_26', 'region_region_27',
       'region_region_28', 'region_region_29', 'region_region_3',
       'region_region_30', 'region_region_31', 'region_region_32',
       'region_region_33', 'region_region_34', 'reg

In [ ]:
from imblearn.over_sampling import SMOTE

x_sample, y_sample = SMOTE().fit_sample(x, y.values.ravel())

x_sample = pd.DataFrame(x_sample)
y_sample = pd.DataFrame(y_sample)

# checking the sizes of the sample data
print("Size of x-sample :", x_sample.shape)
print("Size of y-sample :", y_sample.shape)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


Size of x-sample : (100280, 58)
Size of y-sample : (100280, 1)


In [ ]:
# splitting x and y into train and validation sets

from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x_sample, y_sample, test_size = 0.2, random_state = 0)

print("Shape of x_train: ", x_train.shape)
print("Shape of x_valid: ", x_valid.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_valid: ", y_valid.shape)

Shape of x_train:  (80224, 58)
Shape of x_valid:  (20056, 58)
Shape of y_train:  (80224, 1)
Shape of y_valid:  (20056, 1)


In [ ]:
# standard scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test  = sc.transform(x_test)
x_valid = sc.transform(x_valid)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import average_precision_score

rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
y_p = rfc.predict(x_valid)
rfc_pred = rfc.predict(x_test)

print("Training Accuracy :", rfc.score(x_train, y_train))
print("Testing Accuracy :", f1_score(y_valid, y_p))


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


Training Accuracy : 0.9998753490227363
Testing Accuracy : 0.966039654295882


In [ ]:
from xgboost.sklearn import XGBClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import average_precision_score

xgb = XGBClassifier()
xgb.fit(x_train, y_train)

xgb_pred = xgb.predict(x_test)
y_xgb = xgb.predict(x_valid)
print("Training Accuracy :", xgb.score(x_train, y_train))
print("Testing Accuracy :", f1_score(y_valid, y_xgb))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy : 0.9464873354607101
Testing Accuracy : 0.947081231339442


In [ ]:
from lightgbm import LGBMClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import average_precision_score

lgb = LGBMClassifier()
lgb.fit(x_train, y_train)

lgb_pred = lgb.predict(x_test)
y_lgb = lgb.predict(x_valid)

print("Training Accuracy :", lgb.score(x_train, y_train))
print("Testing Accuracy :", f1_score(y_valid, y_lgb))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Accuracy : 0.9668802353410451
Testing Accuracy : 0.9670295966876246


In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier()
etc.fit(x_train, y_train)

etc_pred = etc.predict(x_test)
y_etc = etc.predict(x_valid)

print("Training Accuracy :", etc.score(x_train, y_train))
print("Testing Accuracy :", f1_score(y_valid, y_etc))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


Training Accuracy : 0.9998753490227363
Testing Accuracy : 0.9666850912014472


In [ ]:
pip install catboost

     |████████████████████████████████| 64.8MB 66kB/s 


In [ ]:
from catboost import CatBoostClassifier

cbc = CatBoostClassifier(learning_rate = 0.004, early_stopping_rounds = 100)
cbc.fit(x_train, y_train)

cbc_pred = cbc.predict(x_test)
y_cbc = cbc.predict(x_valid)

print("Training Accuracy :", rfc.score(x_train, y_train))
print("Testing Accuracy :", f1_score(y_valid, y_cbc))

0:	learn: 0.6891114	total: 119ms	remaining: 1m 58s
1:	learn: 0.6845228	total: 183ms	remaining: 1m 31s
2:	learn: 0.6801127	total: 252ms	remaining: 1m 23s
3:	learn: 0.6757589	total: 314ms	remaining: 1m 18s
4:	learn: 0.6712951	total: 379ms	remaining: 1m 15s
5:	learn: 0.6675942	total: 441ms	remaining: 1m 13s
6:	learn: 0.6633787	total: 505ms	remaining: 1m 11s
7:	learn: 0.6591501	total: 567ms	remaining: 1m 10s
8:	learn: 0.6557026	total: 641ms	remaining: 1m 10s
9:	learn: 0.6522102	total: 702ms	remaining: 1m 9s
10:	learn: 0.6481230	total: 766ms	remaining: 1m 8s
11:	learn: 0.6441222	total: 827ms	remaining: 1m 8s
12:	learn: 0.6402508	total: 893ms	remaining: 1m 7s
13:	learn: 0.6363750	total: 954ms	remaining: 1m 7s
14:	learn: 0.6326900	total: 1.01s	remaining: 1m 6s
15:	learn: 0.6292408	total: 1.08s	remaining: 1m 6s
16:	learn: 0.6256753	total: 1.15s	remaining: 1m 6s
17:	learn: 0.6223238	total: 1.21s	remaining: 1m 6s
18:	learn: 0.6192980	total: 1.28s	remaining: 1m 6s
19:	learn: 0.6159153	total: 1.34

In [ ]:
combi = pd.concat([train, test]) 

In [ ]:
combi.head()

employee_id         department  ... avg_training_score is_promoted
0        65438  Sales & Marketing  ...                 49         0.0
1        65141         Operations  ...                 60         0.0
2         7513  Sales & Marketing  ...                 50         0.0
3         2542  Sales & Marketing  ...                 50         0.0
4        48945         Technology  ...                 73         0.0

[5 rows x 14 columns]

In [ ]:
combi.isnull().sum()

employee_id                 0
department                  0
region                      0
education                3443
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     5936
length_of_service           0
KPIs_met >80%               0
awards_won?                 0
avg_training_score          0
is_promoted             23490
dtype: int64

In [ ]:
combi['education'].value_counts()

Bachelor's          52247
Master's & above    21429
Below Secondary      1179
Name: education, dtype: int64

In [ ]:
combi['education'].fillna("Bachelor's", inplace=True)

In [ ]:
combi.isnull().sum()

employee_id                 0
department                  0
region                      0
education                   0
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     5936
length_of_service           0
KPIs_met >80%               0
awards_won?                 0
avg_training_score          0
is_promoted             23490
dtype: int64

In [ ]:
combi['previous_year_rating'].value_counts()

3.0    26539
5.0    16838
4.0    14126
1.0     8903
2.0     5956
Name: previous_year_rating, dtype: int64

In [ ]:
combi['previous_year_rating'].fillna(3.0, inplace = True)

In [ ]:
combi.isnull().sum()

employee_id                 0
department                  0
region                      0
education                   0
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating        0
length_of_service           0
KPIs_met >80%               0
awards_won?                 0
avg_training_score          0
is_promoted             23490
dtype: int64

In [ ]:
combi.dtypes

employee_id               int64
department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted             float64
dtype: object

In [ ]:
combi['department'].value_counts()

Sales & Marketing    24155
Operations           16112
Procurement          10158
Technology           10149
Analytics             7671
Finance               3627
HR                    3503
Legal                 1484
R&D                   1439
Name: department, dtype: int64

In [ ]:
 replace_values = {'Sales & Marketing' : 1, 'Operations' : 2, 'Procurement' : 3, 'Technology' : 4, 'Analytics' : 5, 'Finance' : 6, 'HR' : 7, 'Legal' : 8, 'R&D' : 9 }                                                                                          

In [ ]:
combi = combi.replace({"department": replace_values})

In [ ]:
combi.head()

employee_id  department  ... avg_training_score is_promoted
0        65438           1  ...                 49         0.0
1        65141           2  ...                 60         0.0
2         7513           1  ...                 50         0.0
3         2542           1  ...                 50         0.0
4        48945           4  ...                 73         0.0

[5 rows x 14 columns]

In [ ]:
combi['region'].value_counts()

region_2     17642
region_22     9167
region_7      6825
region_15     3938
region_13     3815
region_26     3271
region_31     2779
region_4      2478
region_27     2369
region_16     2055
region_28     1913
region_11     1886
region_23     1691
region_29     1408
region_32     1378
region_19     1284
region_14     1177
region_20     1176
region_17     1157
region_25     1156
region_5      1108
region_6       988
region_30      930
region_8       924
region_10      917
region_1       848
region_24      727
region_12      715
region_9       600
region_21      590
region_3       493
region_34      447
region_33      395
region_18       51
Name: region, dtype: int64

In [ ]:
 region_values = {'region_1' : 1, 
                   'region_2' : 2,
                   'region_3' : 3, 
                   'region_4' : 4, 
                   'region_5' : 5,
                   'region_6' : 6,
                   'region_7' : 7, 
                   'region_8' : 8,
                   'region_9' : 9,
                   'region_10' : 10,
                   'region_11' : 11,
                   'region_12' : 12,
                   'region_13' : 13,
                   'region_14' : 14,
                   'region_15' : 15,
                   'region_16' : 16,
                   'region_17' : 17,
                   'region_18' : 18,
                   'region_19' : 19,
                   'region_20' : 20,
                   'region_21' : 21,
                   'region_22' : 22,
                   'region_23' : 23,
                   'region_24' : 24,
                   'region_25' : 25,
                   'region_26' : 26,
                   'region_27' : 27,
                   'region_28' : 28,
                   'region_29' : 29,
                   'region_30' : 30,
                   'region_31' : 31,
                   'region_32' : 32,
                   'region_33' : 33,
                   'region_34' : 34 }                                                                                          

In [ ]:
combi = combi.replace({"region": region_values})

In [ ]:
combi['region']

0         7
1        22
2        19
3        23
4        26
         ..
23485     2
23486    25
23487    16
23488    31
23489    17
Name: region, Length: 78298, dtype: int64

In [ ]:
combi['education'].value_counts()

Bachelor's          55690
Master's & above    21429
Below Secondary      1179
Name: education, dtype: int64

In [ ]:
edu_values = {"Bachelor's": 1, "Master's & above": 2, "Below Secondary" : 3}

In [ ]:
combi = combi.replace({"education":edu_values})

In [ ]:
combi.head()

employee_id  department  ...  avg_training_score  is_promoted
0        65438           1  ...                  49          0.0
1        65141           2  ...                  60          0.0
2         7513           1  ...                  50          0.0
3         2542           1  ...                  50          0.0
4        48945           4  ...                  73          0.0

[5 rows x 14 columns]

In [ ]:
gen_values = {"f": 1, "m": 2}
combi = combi.replace({"gender":gen_values})

In [ ]:
combi['gender'].value_counts()

2    55092
1    23206
Name: gender, dtype: int64

In [ ]:
combi['recruitment_channel'].value_counts()

other       43524
sourcing    33181
referred     1593
Name: recruitment_channel, dtype: int64

In [ ]:
rec_values = {"sourcing": 1, "referred": 2, "other": 3}

In [ ]:
combi = combi.replace({"recruitment_channel":rec_values})

In [ ]:
combi.head()

employee_id  department  ...  avg_training_score  is_promoted
0        65438           1  ...                  49          0.0
1        65141           2  ...                  60          0.0
2         7513           1  ...                  50          0.0
3         2542           1  ...                  50          0.0
4        48945           4  ...                  73          0.0

[5 rows x 14 columns]

In [ ]:
combi.isnull().sum()

employee_id                 0
department                  0
region                      0
education                   0
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating        0
length_of_service           0
KPIs_met >80%               0
awards_won?                 0
avg_training_score          0
is_promoted             23490
dtype: int64

In [ ]:
combi.dtypes

employee_id               int64
department                int64
region                    int64
education                 int64
gender                    int64
recruitment_channel       int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted             float64
dtype: object

In [ ]:
combi.head()

employee_id  department  ...  avg_training_score  is_promoted
0        65438           1  ...                  49          0.0
1        65141           2  ...                  60          0.0
2         7513           1  ...                  50          0.0
3         2542           1  ...                  50          0.0
4        48945           4  ...                  73          0.0

[5 rows x 14 columns]

In [ ]:
combi.shape

(78298, 14)

In [ ]:
combi.corr()

employee_id  department  ...  avg_training_score  is_promoted
employee_id              1.000000    0.000640  ...           -0.003930     0.001206
department               0.000640    1.000000  ...            0.517826     0.002381
region                   0.000025   -0.005873  ...            0.026960    -0.011007
education                0.001926    0.049990  ...            0.038209     0.026244
gender                  -0.000263    0.009595  ...           -0.024840    -0.011109
recruitment_channel     -0.004357    0.009641  ...            0.007212    -0.002229
no_of_trainings         -0.005216   -0.004932  ...            0.044180    -0.024896
age                      0.000586   -0.093586  ...           -0.044592    -0.017166
previous_year_rating     0.001264    0.071646  ...            0.068547     0.153230
length_of_service        0.004420   -0.083033  ...           -0.035272    -0.010670
KPIs_met >80%            0.000127    0.056913  ...            0.076729     0.221582
awards_won?              0.005943    0.003333  ...            0.072655     0.195871
avg_training_score      -0.003930    0.517826  ...            1.000000     0.181147
is_promoted              0.001206    0.002381  ...            0.181147     1.000000

[14 rows x 14 columns]

In [ ]:
train = combi[:54808]
test = combi[54808:]

In [ ]:
train.shape, test.shape

((54808, 14), (23490, 14))

In [ ]:
test = test.drop(['is_promoted'],axis=1)

In [ ]:
test.shape

(23490, 13)

In [ ]:
X = train.drop(['employee_id', 'is_promoted'],axis=1)
y = train['is_promoted']

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X)

In [ ]:
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score,precision_score
f1 = f1_score(y, y_pred,average='weighted')

In [ ]:
f1

0.8950197457242081

In [ ]:
accuracy_score(y, y_pred)

0.9218362282878412

In [ ]:
precision_score(y, y_pred,average='weighted')

0.9098607416742233

In [ ]:
X_tt = test.drop(['employee_id'], axis=1)

In [ ]:
X_tt = sc.transform(X_tt)

In [ ]:
y_predtt = classifier.predict(X_tt)

In [ ]:
y_predtt

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
print(y_predtt)

[0. 0. 0. ... 0. 0. 0.]


In [ ]:
y_predtt[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#for i in range (0, len(y_predtt)): 
 #   print (y_predtt[i], end =" ") 

In [ ]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X, y)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:

# Predicting the Test set results
y_pred = classifier.predict(X)

In [ ]:
f1 = f1_score(y, y_pred,average='weighted')

In [ ]:
f1

0.9901764748329362

In [ ]:
accuracy_score(y, y_pred)

0.9904211064078237

In [ ]:
y_predtt = classifier.predict(X_tt)

In [ ]:
y_predtt

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
import lightgbm as ltb

In [ ]:
model = ltb.LGBMClassifier()
model.fit(X, y)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
y_pred = model.predict(X)

In [ ]:
f1 = f1_score(y, y_pred,average='weighted')

In [ ]:
f1

0.9330102821402861

In [ ]:
y_predtt = model.predict(X_tt)

In [ ]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X, y)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X)

In [ ]:
f1 = f1_score(y, y_pred,average='weighted')

In [ ]:
f1

0.8741390743005856

In [ ]:
y_predtt = classifier.predict(X_tt)

In [ ]:
y_predtt

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
pip install catboost

     |████████████████████████████████| 64.8MB 70kB/s 


In [ ]:
from catboost import CatBoostRegressor
model=CatBoostRegressor(iterations=50, depth=3, learning_rate=0.1, loss_function='RMSE')
model.fit(X, y)

0:	learn: 0.2751523	total: 8.18ms	remaining: 401ms
1:	learn: 0.2719341	total: 15.9ms	remaining: 382ms
2:	learn: 0.2691269	total: 25.4ms	remaining: 398ms
3:	learn: 0.2668624	total: 32.7ms	remaining: 376ms
4:	learn: 0.2650364	total: 40ms	remaining: 360ms
5:	learn: 0.2632085	total: 47.1ms	remaining: 345ms
6:	learn: 0.2618179	total: 54.6ms	remaining: 335ms
7:	learn: 0.2605625	total: 61.7ms	remaining: 324ms
8:	learn: 0.2594344	total: 68.9ms	remaining: 314ms
9:	learn: 0.2584359	total: 76ms	remaining: 304ms
10:	learn: 0.2575671	total: 83.1ms	remaining: 295ms
11:	learn: 0.2568355	total: 90.5ms	remaining: 286ms
12:	learn: 0.2549747	total: 97.7ms	remaining: 278ms
13:	learn: 0.2543811	total: 105ms	remaining: 271ms
14:	learn: 0.2533052	total: 113ms	remaining: 263ms
15:	learn: 0.2516020	total: 120ms	remaining: 256ms
16:	learn: 0.2510522	total: 128ms	remaining: 248ms
17:	learn: 0.2496636	total: 135ms	remaining: 241ms
18:	learn: 0.2485975	total: 143ms	remaining: 234ms
19:	learn: 0.2482835	total: 150m

In [ ]:
y_pred = classifier.predict(X)

In [ ]:
f1 = f1_score(y, y_pred,average='weighted')

In [ ]:
f1

0.8741390743005856

In [ ]:
y_predtt = classifier.predict(X_tt)

In [ ]:
y_predtt

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
model = XGBClassifier()
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
y_pred = model.predict(X)

In [ ]:
f1 = f1_score(y, y_pred, average='weighted')

In [ ]:
f1

0.9215178589817299

In [ ]:
y_predtt = model.predict(X_tt)

In [ ]:
y_predtt

array([0., 0., 0., ..., 0., 0., 1.])

In [ ]:
rfc_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
etc_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
lgb_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
xgb_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
cbc_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
boosted_predictions = rfc_pred*0.2 + xgb_pred*0.2 + lgb_pred*0.4 + etc_pred*0.3

In [ ]:
st = pd.read_csv("sample_submission.csv")

In [ ]:
st.head()

employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

In [ ]:
st['is_promoted'] = boosted_predictions

In [ ]:
st.head()

employee_id  is_promoted
0         8724          0.0
1        74430          0.0
2        72255          0.0
3        38562          0.0
4        64486          0.0

In [ ]:
st['is_promoted'] = st['is_promoted'].astype((int))

In [ ]:
st.head()

employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

In [ ]:
st['is_promoted'].value_counts()

0    23119
1      371
Name: is_promoted, dtype: int64

In [ ]:
train['is_promoted'].value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [ ]:
st.to_csv("sub_bp.csv",index=False)